before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ vivid main universe"
  - sudo apt-get -qq update
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch

install:
  - sudo apt-get install --yes --force-yes circos build-essential wget fasttree hmmer lua5.1 blast2 ncbi-blast+ unzip cpanminus mummer python-setuptools exonerate snap infernal mafft telnet libboost-iostreams-dev libgsl0ldbl libcolamd2.8.0 libstdc++6
  - sudo ln -s /usr/bin/fasttree /usr/bin/FastTree
  - sudo test/travis.setup-augustus.sh > /dev/null
  - sudo test/travis.setup-gt.sh > /dev/null
  - sudo test/travis.setup-last.sh > /dev/null 
  - sudo test/travis.setup-orthomcl.sh > /dev/null
  - sudo test/travis.setup-aragorn.sh > /dev/null
  - sudo test/travis.setup-gff3toembl.sh > /dev/null
  - sudo cpanm -q --force Carp Storable Bio::SearchIO List::Util Getopt::Long
  - curl -fsSL get.nextflow.io | bash
  - wget -q http://geneontology.org/ontology/go.obo
  - travis_wait wget -q http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
  - zcat Pfam-A.hmm.gz | test/split-hmm.lua 1000 > Pfam-A.hmm
  - travis_wait hmmpress Pfam-A.hmm
  - rm -f Pfam-A.hmm

cache:
  directories:
    - work
env:
  global:
    - ROOTDIR="$TRAVIS_BUILD_DIR"
script:
  - cd test/testsuite
  - ./testsuite.rb -threads 2
  - cd ../..
  - travis_wait ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false
  - travis_wait ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --run_exonerate=true
  - travis_wait ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --do_pseudo=false
  - travis_wait ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --run_snap=false
